# Arrays vs Lists

In [25]:
import numpy as np

In [4]:
L = [1,2,3]
A = np.array()

In [5]:
for e in L:
    print(e)

1
2
3


In [6]:
for e in A:
    print(e)

1
2
3


In [9]:
L.append(4)

In [10]:
A.append(4)
# Arrays are fixed!

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
A + np.array([4])
# Adds element (4) to every number in the array.

array([5, 6, 7])

In [12]:
A + np.array([4,5,6])
# Adds elements to the array in the same order

array([5, 7, 9])

In [15]:
2 * L

[1, 2, 3, 4, 4, 4, 1, 2, 3, 4, 4, 4]

In [16]:
2 * A

array([2, 4, 6])

In [19]:
L2 = []
for e in L:
    L2.append(e+3)

In [20]:
L2

[4, 5, 6, 7, 7, 7]

In [21]:
L2 = [e+3 for e in L]
L2

[4, 5, 6, 7, 7, 7]

In [22]:
# Let's try squareing everything.
L2 = []
for e in L:
    L2.append(e**2)

In [23]:
L2

[1, 4, 9, 16, 16, 16]

In [27]:
# Numpy makes this very easy. No need for loops.
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

# The Dot Product

In [28]:
a = np.array([1,2])
b = np.array([3,4])

In [29]:
dot = 0
for e, f in zip(a,b):
    dot += e*f
dot

11

In [30]:
dot = 0
for i in range(len(a)):
    dot += a[i] * b[i]
dot

11

In [31]:
a * b

array([3, 8])

In [32]:
np.sum(a * b)

11

In [33]:
(a * b).sum()

11

In [34]:
# Using numpy
np.dot(a,b)

11

In [35]:
a @ b

11

In [36]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [37]:
np.linalg.norm(a)

2.23606797749979

In [38]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [40]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

# Speed Test
How much faster is numpy than using other methods?

In [44]:
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 10000

def slow_dot_product(a,b):
    result = 0
    for e, f in zip(a,b):
        result += e*f
    return result

t0 = datetime.now()
for t in range(T):
    slow_dot_product(a,b)
dt1 = datetime.now() - t0

t0=datetime.now()
for t in range(T):
    a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 79.37811358352708


Using numpy is MUCH faster!

# Matrices

In [45]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [46]:
L[0]
# Rows, Columns

[1, 2]

In [47]:
L[0][1]

2

In [50]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [51]:
A[0,1]

2

In [52]:
A[:,0]
# : Means select every row

array([1, 3])

In [53]:
# We can apply functions using numpy
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

# Solving Linear Systems

The admission fee at a small fair is 1.50 for children and 4.00 for adults. On a certain day, 2200 people enter the fair and 5050 is collected. How many children and how many adults attended?

$x_1 + x_2 = 2200$

$1.5x_1 + 4x_2 = 5050$

In [57]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

In [58]:
np.linalg.solve(A,b)

array([1500.,  700.])

# Generating Data

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.random.random()

0.032807837436457654

In [64]:
np.random.random((2,3))

array([[0.24187334, 0.83342506, 0.78622319],
       [0.79587555, 0.07859234, 0.56628245]])

In [65]:
np.random.randn(2,3)

array([[-0.38924487, -1.46892876,  0.19155979],
       [ 1.22501032, -0.78280033, -1.6769213 ]])

In [66]:
R = np.random.randn(10000)

In [67]:
R.mean()

0.012913312602158339

In [68]:
np.mean(R)

0.012913312602158339

In [69]:
np.var(R)

1.0232225697931332

In [70]:
R = np.random.randn(10000,3)

In [72]:
R.mean(axis=0)

array([-0.01031491,  0.00534951,  0.00415976])

In [73]:
R.mean(axis=1).shape

(10000,)

In [74]:
np.random.randint(0,10, size = (3,3))

array([[3, 0, 8],
       [3, 7, 8],
       [0, 0, 4]])

# Exercise

In [92]:
from datetime import datetime
a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

L1=[]
L2=[]

for e, f in zip(a, b):
  L1.append(e)
  L2.append(f)

def slow_matrix_multiplication(L1, L2):
  result = 0
  for i in range(len(L1)):
    result += L1[i]*L2[i]
  return result

t0 = datetime.now()
for t in range(T):
  slow_matrix_multiplication(L1, L2)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2: ", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2:  42.51714253438391
